[pytest]
testpaths = Tests
python_files = test_*.py
addopts =
    --cov=commands.postProcessor.line
    --cov=_makera_community_addin.commands.postProcessor.operations.operation.rapidsParser
    --cov=_makera_community_addin.commands.postProcessor.operations.operation.parser
    --cov=_makera_community_addin.commands.postProcessor.settings.settings
    --cov-report=term-missing
    --cov-report=html
